# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [ '--maxkb=2048' ]
      - id: sort-simple-yaml
  - repo: https://gitlab.com/lrkwz/my-git-hooks
    rev: v1.1.0
    hooks:
      - id: no-wip-in-main-develop
      - id: no-commit-in-main-or-master
